version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["maintenance", "ignore-for-release"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: uv
    directory: "/"
    labels: ["maintenance", "ignore-for-release"]
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
