"""
MIF (Fixel-wise) Data Conversion
================================

To convert fixel-wise data in MIF format to HDF5 format,
use the ``modelarrayio to-modelarray`` command to convert the MIF files to the HDF5 format
(``.h5``) used by **ModelArray**,
and ``modelarrayio export-results`` to export results back to MIF.
This guide assumes **ModelArrayIO** is already installed.
"""

# %%
# Prepare data
# ------------
#
# To convert a list of fixel-wise data from ``.mif`` to ``.h5`` format, prepare a cohort CSV
# file that describes every ``.mif`` file you want to include.
#
# The cohort CSV may use either of these layouts:
#
# * **Long format:** one row per subject and scalar, with the fixed columns ``scalar_name`` and
#   ``source_file``.
# * **Wide format:** one row per subject, with a separate file-path column for each scalar
#   (for example, ``FD`` and ``FC``). Pass those column names to ``--scalar-columns``.
#
# Other columns, such as subject IDs and demographics, may appear alongside the path columns.

# %%
# Example folder structure
# ------------------------
#
# .. code-block:: text
#
#     /home/username/myProject/data
#     |
#     ├── cohort_FD.csv
#     ├── cohort_wide.csv
#     │
#     ├── FD
#     │   ├── index.mif
#     │   ├── directions.mif
#     │   ├── sub-01_fd.mif
#     │   ├── sub-02_fd.mif
#     │   ├── sub-03_fd.mif
#     │   └── ...
#     │
#     ├── FC
#     │   ├── index.mif
#     │   ├── directions.mif
#     │   ├── sub-01_fc.mif
#     │   ├── sub-02_fc.mif
#     │   ├── sub-03_fc.mif
#     │   └── ...
#     └── ...
#
# These ``.mif`` files are generated by MRtrix.
#
# Long-format cohort CSV
# ----------------------
#
# Corresponding ``cohort_FD.csv`` for scalar FD:
#
# .. list-table::
#    :header-rows: 1
#    :widths: auto
#
#    * - **scalar_name** *(required)*
#      - **source_file** *(required)*
#      - subject_id
#      - age
#      - sex
#    * - FD
#      - /home/username/myProject/data/FD/sub-01_fd.mif
#      - sub-01
#      - 10
#      - F
#    * - FD
#      - /home/username/myProject/data/FD/sub-02_fd.mif
#      - sub-02
#      - 20
#      - M
#    * - FD
#      - /home/username/myProject/data/FD/sub-03_fd.mif
#      - sub-03
#      - 15
#      - F
#    * - ...
#      - ...
#      - ...
#      - ...
#      - ...
#
# Notes:
#
# * Column order does not matter.
# * Values are case-sensitive — folder names, file names, and scalar names must match exactly
#   between the CSV and disk.

# %%
# Wide-format cohort CSV
# ----------------------
#
# A wide CSV stores all scalar paths for a subject on one row. For example,
# ``cohort_wide.csv`` can contain both FD and FC:
#
# .. list-table::
#    :header-rows: 1
#    :widths: auto
#
#    * - subject_id
#      - **FD**
#      - **FC**
#      - age
#      - sex
#    * - sub-01
#      - /home/username/myProject/data/FD/sub-01_fd.mif
#      - /home/username/myProject/data/FC/sub-01_fc.mif
#      - 10
#      - F
#    * - sub-02
#      - /home/username/myProject/data/FD/sub-02_fd.mif
#      - /home/username/myProject/data/FC/sub-02_fc.mif
#      - 20
#      - M
#    * - ...
#      - ...
#      - ...
#      - ...
#      - ...
#
# ``FD`` and ``FC`` are user-defined scalar column names. The files must use the fixel layout
# described by the supplied ``index.mif`` and ``directions.mif`` files.

# %%
# Convert .mif files to HDF5
# --------------------------
#
# Using the FD dataset from the example above:
#
# .. code-block:: console
#
#     # activate your conda environment first
#     conda activate <env_name>
#
#     modelarrayio to-modelarray \
#         --index-file      /home/username/myProject/data/FD/index.mif \
#         --directions-file /home/username/myProject/data/FD/directions.mif \
#         --cohort-file     /home/username/myProject/data/cohort_FD.csv \
#         --output          /home/username/myProject/data/FD.h5
#
# This produces ``FD.h5`` in ``/home/username/myProject/data``.  You can then use
# `ModelArray <https://pennlinc.github.io/ModelArray/>`_ to run statistical analyses on it.

# %%
# Convert a wide-format cohort
# ----------------------------
#
# Name each scalar path column with ``--scalar-columns``:
#
# .. code-block:: console
#
#     modelarrayio to-modelarray \
#         --index-file      /home/username/myProject/data/FD/index.mif \
#         --directions-file /home/username/myProject/data/FD/directions.mif \
#         --cohort-file     /home/username/myProject/data/cohort_wide.csv \
#         --scalar-columns  FD FC \
#         --output          /home/username/myProject/data/modelarray.h5
#
# Wide cohorts write one output per scalar by default. This command creates
# ``FD_modelarray.h5`` and ``FC_modelarray.h5``. Add ``--no-split-files`` to store both
# scalars in the single ``modelarray.h5`` output instead.

# %%
# Convert result .h5 back to .mif files
# --------------------------------------
#
# After running ModelArray and obtaining statistical results inside ``FD.h5`` (suppose the
# analysis name is ``"mylm"``), use ``modelarrayio export-results`` to export them as ``.mif`` files.
# The command also copies the original ``index.mif`` and ``directions.mif`` into the output
# folder.
#
# .. code-block:: console
#
#     modelarrayio export-results \
#         --index-file      /home/username/myProject/data/FD/index.mif \
#         --directions-file /home/username/myProject/data/FD/directions.mif \
#         --cohort-file     /home/username/myProject/data/cohort_FD.csv \
#         --analysis-name   mylm \
#         --input-hdf5      /home/username/myProject/data/FD.h5 \
#         --output-dir      /home/username/myProject/data/FD_stats
#
# The results in ``FD_stats`` can now be viewed in ``mrview``.
#
# .. warning::
#
#    **Existing files are not overwritten.** With ``modelarrayio export-results``, any ``.mif`` file
#    already present in ``--output-dir`` with the same name
#    will be left unchanged.  If ``--output-dir`` itself already exists you will see a
#    ``WARNING: Output directory exists`` message, but no files will be deleted.  To start
#    fresh, manually remove the output directory before re-running ``modelarrayio export-results``.

# %%
# Additional help
# ---------------
#
# Full argument documentation is available from the command line:
#
# .. code-block:: console
#
#     modelarrayio to-modelarray --help
#     modelarrayio export-results --help
#
# or in the :doc:`/usage` page of this documentation.
